class ColorHandlers:
    @staticmethod
    def change_color(key):
        match key:
            case "薬剤使用状況の把握等（情報収集）":
                return "#384B70"
            case "服薬指導＋指導記録作成":
                return "#384B70"
            case "混注時間":
                return "#384B70"
            case "無菌調製関連業務":
                return "#384B70"
            case "薬剤セット・確認":
                return "#384B70"
            case "持参薬を確認":
                return "#384B70"
            case "薬剤服用歴等について保険薬局へ照会":
                return "#384B70"
            case "処方代理修正":
                return "#384B70"
            case "TDM実施":
                return "#384B70"
            case "カンファレンス":
                return "#384B70"
            case "医師からの相談":
                return "#384B70"
            case "看護師からの相談":
                return "#384B70"
            case "その他の職種からの相談":
                return "#384B70"
            case "委員会":
                return "#507687"
            case "勉強会参加":
                return "#507687"
            case "WG活動":
                return "#507687"
            case "1on1":
                return "#507687"
            case "ICT/AST":
                return "#507687"
            case "褥瘡":
                return "#507687"
            case "TPN評価":
                return "#507687"
            case "手術後使用薬剤確認":
                return "#508D4E"
            case "手術使用薬剤準備":
                return "#508D4E"
            case "周術期薬剤管理関連":
                return "#508D4E"
            case "麻酔科周術期外来":
                return "#508D4E"
            case "手術使用麻薬確認・補充":
                return "#508D4E"
            case "術後疼痛管理チーム回診":
                return "#508D4E"
            case "脳卒中ホットライン対応":
                return "#508D4E"
            case "業務調整":
                return "#72BAA9"
            case "休憩":
                return "#72BAA9"
            case "その他":
                return "#72BAA9"
            case "管理業務":
                return "#72BAA9"
            case "NST":
                return "#507687"
            case "問い合わせ応需":
                return "#DDA853"
            case "マスター作成・変更":
                return "#DDA853"
            case "薬剤情報評価":
                return "#DDA853"
            case "後発品選定":
                return "#DDA853"
            case "会議資料作成":
                return "#DDA853"
            case "配信資料作成":
                return "#DDA853"
            case "フォーミュラリー作成":
                return "#DDA853"
            case "外来処方箋修正":
                return "#DDA853"
            case "勉強会資料作成・開催":
                return "#DDA853"
            case "お役立ち情報作成":
                return "#DDA853"
            case "薬剤使用期限確認":
                return "#508D4E"
