class ColorHandlers:
    @staticmethod
    def change_color(key):
        match key:
            case "初回・中間指導情報収集":
                return "#384B70"
            case "他院指導情報収集":
                return "#384B70"
            case "注射台車監査":
                return "#384B70"
            case "服薬指導":
                return "#384B70"
            case "指導記録作成":#4
                return "#384B70"
            case "無菌調製(調製者)":#5
                return "#384B70"
            case "無菌調製補助業務（準備、監査）":#6
                return "#384B70"
            case "薬剤セット":#7
                return "#384B70"
            case "薬剤セット確認":
                return "#384B70"
            case "持参薬を確認":
                return "#384B70"
            case "薬剤服用歴等について保険薬局へ照会":#10
                return "#384B70"
            case "薬剤サマリー作成":#11
                return "#384B70"
            case "処方代理修正・代行入力":#12
                return "#384B70"
            case "TDM実施":#13
                return "#384B70"
            case "カンファレンス":#14
                return "#384B70"
            case "問い合わせ業務":#15
                return "#384B70"
            case "委員会":#16
                return "#507687"
            case "勉強会参加":#17
                return "#507687"
            case "WG活動":#18
                return "#507687"
            case "1on1":#19
                return "#507687"
            case "ICT":
                return "#507687"
            case "AST":
                return "#507687"
            case "抗菌薬相談対応":
                return "#507687"
            case "褥瘡":
                return "#507687"
            case "TPN評価":
                return "#507687"
            case "手術後使用薬剤確認":
                return "#508D4E"
            case "手術使用薬剤準備":
                return "#508D4E"
            case "周術期薬剤管理記録作成":
                return "#508D4E"
            case "周術期薬剤管理準備":
                return "#508D4E"
            case "周術期薬剤管理記録作成":
                return "#508D4E"
            case "麻酔科周術期外来予約確認":
                return "#508D4E"
            case "麻酔科周術期外来情報収集":
                return "#508D4E"
            case "麻酔科周術期外来":
                return "#508D4E"
            case "麻酔科周術期外来記録":
                return "#508D4E"
            case "手術使用麻薬確認・補充":
                return "#508D4E"
            case "APSチーム回診情報収集":
                return "#508D4E"
            case "APSチーム回診":
                return "#508D4E"
            case "APS関連記録作成":
                return "#508D4E"
            case "脳卒中ホットライン対応":
                return "#508D4E"
            case "手術使用薬剤確認・補充":
                return "#508D4E"
            case "注射薬調製":
                return "#508D4E"
            case "金庫管理定数確認":
                return "#508D4E"
            case "業務調整":
                return "#72BAA9"
            case "休憩":
                return "#72BAA9"
            case "その他":
                return "#72BAA9"
            case "管理業務":
                return "#72BAA9"
            case "NST":
                return "#507687"
            case "マスター作成・変更":
                return "#DDA853"
            case "薬剤情報評価":
                return "#DDA853"
            case "後発品選定":
                return "#DDA853"
            case "会議資料作成":
                return "#DDA853"
            case "配信資料作成":
                return "#DDA853"
            case "フォーミュラリー作成":
                return "#DDA853"
            case "外来処方箋修正":
                return "#DDA853"
            case "勉強会資料作成・開催":
                return "#DDA853"
            case "お役立ち情報作成":
                return "#DDA853"
            case "薬剤使用期限確認":
                return "#508D4E"
            case "緩和回診":
                return "#507687"
            case "心不全回診":
                return "#507687"
            case "緩和回診記録作成":
                return "#507687"
            case "手術室サテライト薬剤定数確認":
                return "#508D4E"
            case "ICTリンクスタッフ活動":
                return "#72BAA9"
            case "医療安全対策WG活動":
                return "#72BAA9"
            case "実習生対応":
                return "#72BAA9"
            case "薬剤部連絡会":
                return "#72BAA9"
            case _:
                return "#384B70"  # Default color for unknown tasks
            
