name: Flet Windows based on PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: pip install -r requirements.txt
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flet pandas datetime numpy

      - name: Build executable
        run: |
          flet build windows app/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/main.exe
